name: Deploy Subgraph to CR QA

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: cr-qa
      subgraphId: rootstockcollective-collective-rewards-cr-qa
      networkName: rootstock-testnet
      graphUrl: https://api.studio.thegraph.com/deploy/
      environmentName: cr-qa
    secrets: inherit
