name: Deploy Subgraph to Release Candidate Mainnet

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: release-candidate-mainnet
      subgraphId: rootstockcollective-collective-rewards-release-candidate-mainnet
      networkName: rootstock
      graphUrl: https://api.studio.thegraph.com/deploy/
      environmentName: release-candidate-mainnet
    secrets: inherit
