name: Deploy Subgraph to Release Candidate Testnet

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: release-candidate-testnet
      subgraphId: rootstockcollective-collective-rewards-release-candidate-testnet
      networkName: rootstock-testnet
      graphUrl: https://api.studio.thegraph.com/deploy/
      environmentName: release-candidate-testnet
    secrets: inherit
